import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router";
import { useConfigEditor } from "../hooks/useConfigEditor";
import { useDevices } from "../hooks/useDevices";
import type { DeviceProfile } from "../schema/deviceProfileSchema";
import type { DeviceRef } from "../schema/systemConfigSchema";
import { loadIntegrationProof, type IntegrationProofResponse } from "../api/integrationProofApi";

const ROLE_PRESETS = ["display", "audio", "source", "lighting", "shades", "hvac", "security", "control"];

type CodeTab = "simpl" | "csharp";

function inferProtocol(profile: DeviceProfile): DeviceRef["protocol"] {
  if (profile.protocols.ip) return "ip";
  if (profile.protocols.serial) return "serial";
  if (profile.protocols.ir) return "ir";
  return "ip";
}

function initialSimplCode(projectName: string) {
  return `#SYMBOL_NAME "${projectName} Core"
#HINT "Generated by Configure Studio"
#CATEGORY "46"

DIGITAL_INPUT init;
DIGITAL_OUTPUT ready_fb;
STRING_INPUT command$;
STRING_OUTPUT status$;

PUSH init
{
  ready_fb = 1;
  status$ = "READY";
}

CHANGE command$
{
  status$ = command$;
}

Function Main()
{
  ready_fb = 0;
  status$ = "BOOT";
}`;
}

function initialCSharpCode(projectId: string) {
  return `using System;

namespace ${projectId.replace(/[^a-zA-Z0-9]/g, "_")}.Control
{
    public class RuntimeController
    {
        public void Initialize()
        {
        }

        public void HandleSignal(string key, object value)
        {
        }
    }
}`;
}

export default function ConfigureStudioPage() {
  const {
    draft,
    assignDevice,
    removeDevice,
    save,
    saveStatus,
    validationErrors,
    isDirty,
  } = useConfigEditor();
  const devices = useDevices();

  const [selectedRoomId, setSelectedRoomId] = useState<string>("");
  const [roleKey, setRoleKey] = useState("display");
  const [search, setSearch] = useState("");
  const [activeCodeTab, setActiveCodeTab] = useState<CodeTab>("simpl");
  const [simplCode, setSimplCode] = useState("");
  const [csharpCode, setCsharpCode] = useState("");
  const [dropHint, setDropHint] = useState("Drop a device here to assign it to the selected room role.");
  const [proofLoading, setProofLoading] = useState(false);
  const [proofError, setProofError] = useState<string | null>(null);
  const [proof, setProof] = useState<IntegrationProofResponse | null>(null);

  useEffect(() => {
    if (!draft) return;
    if (!selectedRoomId && draft.rooms.length > 0) {
      setSelectedRoomId(draft.rooms[0].id);
    }

    const keyBase = `studio-code-${draft.projectId}`;
    const storedSimpl = localStorage.getItem(`${keyBase}-simpl`);
    const storedCSharp = localStorage.getItem(`${keyBase}-csharp`);
    setSimplCode(storedSimpl ?? initialSimplCode(draft.system.name));
    setCsharpCode(storedCSharp ?? initialCSharpCode(draft.projectId));
  }, [draft, selectedRoomId]);

  useEffect(() => {
    if (!draft) return;
    const keyBase = `studio-code-${draft.projectId}`;
    localStorage.setItem(`${keyBase}-simpl`, simplCode);
    localStorage.setItem(`${keyBase}-csharp`, csharpCode);
  }, [draft, simplCode, csharpCode]);

  const selectedRoom = useMemo(() => draft?.rooms.find((room) => room.id === selectedRoomId) ?? null, [draft, selectedRoomId]);

  const filteredDevices = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return devices.data;
    return devices.data.filter((device) => {
      return (
        device.id.toLowerCase().includes(q)
        || device.model.toLowerCase().includes(q)
        || device.manufacturer.toLowerCase().includes(q)
        || device.category.toLowerCase().includes(q)
      );
    });
  }, [devices.data, search]);

  const handleAssign = (profile: DeviceProfile) => {
    if (!selectedRoom) return;
    const trimmedRole = roleKey.trim().toLowerCase();
    if (!trimmedRole) return;

    assignDevice(selectedRoom.id, trimmedRole, {
      profileId: profile.id,
      protocol: inferProtocol(profile),
    });
    setDropHint(`Assigned ${profile.model} to role '${trimmedRole}'.`);
  };

  const handleDrop = (event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    const deviceId = event.dataTransfer.getData("text/plain");
    if (!deviceId) return;
    const profile = devices.data.find((item) => item.id === deviceId);
    if (!profile) return;
    handleAssign(profile);
  };

  const addIntegrationPack = (pack: "bacnet" | "knx" | "lutron-qsx" | "lutron-qs-telnet") => {
    if (!selectedRoom) return;

    if (pack === "bacnet") {
      assignDevice(selectedRoom.id, "bacnet-gateway", {
        profileId: "bacnet-ip-gateway-v1",
        protocol: "bacnet",
        address: "192.168.1.150",
        objectId: 1001,
      });
      setDropHint("BACnet integration pack added.");
      return;
    }

    if (pack === "knx") {
      assignDevice(selectedRoom.id, "knx-gateway", {
        profileId: "knx-ip-interface-v1",
        protocol: "knx",
        address: "1.1.1/1/0/1",
      });
      setDropHint("KNX integration pack added.");
      return;
    }

    if (pack === "lutron-qsx") {
      assignDevice(selectedRoom.id, "lutron-qsx", {
        profileId: "lutron-qsx-processor",
        protocol: "ip",
        address: "192.168.1.200",
        port: "8081",
      });
      setDropHint("Lutron QSX integration pack added.");
      return;
    }

    assignDevice(selectedRoom.id, "lutron-qs-telnet", {
      profileId: "lutron-qs-telnet",
      protocol: "ip",
      address: "192.168.1.201",
      port: "23",
    });
    setDropHint("Lutron QS Telnet integration pack added.");
  };

  const handleRefreshProof = async () => {
    setProofLoading(true);
    setProofError(null);
    try {
      const result = await loadIntegrationProof();
      setProof(result);
    } catch (e: unknown) {
      setProofError(e instanceof Error ? e.message : "Failed to load proof report");
    } finally {
      setProofLoading(false);
    }
  };

  if (!draft) {
    return (
      <div className="card">
        <h2>Studio</h2>
        <p className="subhead">Load or create a draft first.</p>
      </div>
    );
  }

  const totalAssigned = draft.rooms.reduce((sum, room) => sum + Object.keys(room.devices).length, 0);

  return (
    <div>
      <div className="page-header">
        <div>
          <h1>SIMPL+ Studio</h1>
          <p className="subhead">Project tree, drag/drop device assignment, and full SIMPL+/C# editing in one place.</p>
        </div>
      </div>

      <section className="grid" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", marginBottom: 16 }}>
        <div className="card stat-card"><p className="stat-value">{draft.rooms.length}</p><p className="stat-label">Rooms</p></div>
        <div className="card stat-card"><p className="stat-value">{totalAssigned}</p><p className="stat-label">Assigned Devices</p></div>
        <div className="card stat-card"><p className="stat-value">{validationErrors.length}</p><p className="stat-label">Validation Errors</p></div>
        <div className="card stat-card"><p className="stat-value">{isDirty ? "Draft" : "Saved"}</p><p className="stat-label">Config State</p></div>
      </section>

      <div className="grid" style={{ gridTemplateColumns: "260px 1fr 1fr", alignItems: "start" }}>
        <div className="card" style={{ position: "sticky", top: 16 }}>
          <p className="label">Project Tree</p>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {draft.rooms.map((room) => {
              const active = room.id === selectedRoomId;
              return (
                <button
                  key={room.id}
                  className="button"
                  style={{
                    textAlign: "left",
                    background: active ? "var(--accent-soft)" : undefined,
                    border: active ? "1px solid var(--accent)" : "1px solid var(--border-default)",
                  }}
                  onClick={() => setSelectedRoomId(room.id)}
                >
                  <strong>{room.name}</strong>
                  <div style={{ fontSize: 12, opacity: 0.8 }}>{room.id} · {Object.keys(room.devices).length} devices</div>
                </button>
              );
            })}
          </div>

          <div style={{ marginTop: 12, display: "flex", gap: 8, flexWrap: "wrap" }}>
            <Link to="/project" className="button" style={{ textDecoration: "none" }}>Overview</Link>
            <Link to="/configure/rooms" className="button" style={{ textDecoration: "none" }}>Rooms</Link>
            <Link to="/validate" className="button" style={{ textDecoration: "none" }}>Validate</Link>
          </div>
        </div>

        <div className="card">
          <p className="label">Device Assignment (Drag & Drop)</p>
          <div className="form-row" style={{ marginBottom: 10 }}>
            <div className="form-group" style={{ flex: 1, marginBottom: 0 }}>
              <label className="label">Role Key</label>
              <input
                className="input"
                list="role-presets"
                value={roleKey}
                onChange={(e) => setRoleKey(e.target.value)}
                placeholder="display"
              />
              <datalist id="role-presets">
                {ROLE_PRESETS.map((role) => <option key={role} value={role} />)}
              </datalist>
            </div>
            <div className="form-group" style={{ flex: 1, marginBottom: 0 }}>
              <label className="label">Search Device</label>
              <input className="input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="model, id, mfr..." />
            </div>
          </div>

          <div
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleDrop}
            style={{
              border: "2px dashed var(--border-default)",
              borderRadius: 12,
              padding: 10,
              marginBottom: 10,
              background: "var(--bg-muted)",
              color: "var(--text-secondary)",
            }}
          >
            <strong>Drop Zone ({selectedRoom?.name ?? "No room selected"})</strong>
            <div style={{ fontSize: 13, marginTop: 4 }}>{dropHint}</div>
          </div>

          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 10 }}>
            <button className="button" onClick={() => addIntegrationPack("bacnet")}>+ BACnet Pack</button>
            <button className="button" onClick={() => addIntegrationPack("knx")}>+ KNX Pack</button>
            <button className="button" onClick={() => addIntegrationPack("lutron-qsx")}>+ Lutron QSX Pack</button>
            <button className="button" onClick={() => addIntegrationPack("lutron-qs-telnet")}>+ Lutron QS Telnet Pack</button>
          </div>

          <div style={{ maxHeight: 320, overflow: "auto", display: "flex", flexDirection: "column", gap: 6 }}>
            {filteredDevices.map((profile) => (
              <div
                key={profile.id}
                draggable
                onDragStart={(e) => e.dataTransfer.setData("text/plain", profile.id)}
                style={{
                  border: "1px solid var(--border-default)",
                  borderRadius: 8,
                  padding: "8px 10px",
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 8,
                  alignItems: "center",
                  background: "var(--bg-surface)",
                }}
              >
                <div>
                  <strong>{profile.model}</strong>
                  <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{profile.id} · {profile.manufacturer}</div>
                </div>
                <button className="button" onClick={() => handleAssign(profile)}>Assign</button>
              </div>
            ))}
          </div>
        </div>

        <div className="card">
          <p className="label">Code Workspace</p>
          <div style={{ display: "flex", gap: 8, marginBottom: 10 }}>
            <button className={`button ${activeCodeTab === "simpl" ? "primary" : ""}`} onClick={() => setActiveCodeTab("simpl")}>SIMPL+</button>
            <button className={`button ${activeCodeTab === "csharp" ? "primary" : ""}`} onClick={() => setActiveCodeTab("csharp")}>C#</button>
          </div>

          {activeCodeTab === "simpl" ? (
            <textarea
              className="editor"
              style={{ minHeight: 360 }}
              value={simplCode}
              onChange={(e) => setSimplCode(e.target.value)}
            />
          ) : (
            <textarea
              className="editor"
              style={{ minHeight: 360 }}
              value={csharpCode}
              onChange={(e) => setCsharpCode(e.target.value)}
            />
          )}

          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
            <button className="button primary" onClick={save} disabled={saveStatus === "saving" || validationErrors.length > 0}>
              {saveStatus === "saving" ? "Saving..." : "Save Config"}
            </button>
            <Link to="/configure/export" className="button" style={{ textDecoration: "none" }}>Review Export</Link>
            <Link to="/configure/deploy" className="button" style={{ textDecoration: "none" }}>Deploy</Link>
          </div>

          {validationErrors.length > 0 && (
            <div style={{ marginTop: 10 }}>
              {validationErrors.slice(0, 4).map((err) => (
                <p key={err} style={{ margin: "0 0 4px", color: "var(--danger)", fontWeight: 600 }}>• {err}</p>
              ))}
            </div>
          )}
        </div>
      </div>

      {selectedRoom && (
        <div className="card" style={{ marginTop: 16 }}>
          <p className="label">Room Overview</p>
          <h3 style={{ marginTop: 0 }}>{selectedRoom.name}</h3>
          <p className="subhead">ID: {selectedRoom.id} · Join offset: {selectedRoom.joinOffset}</p>

          <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 10 }}>
            {selectedRoom.subsystems.map((sub) => <span key={sub} className={`pill pill--${sub}`}>{sub}</span>)}
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {Object.entries(selectedRoom.devices).map(([role, device]) => (
              <div key={role} style={{ display: "flex", justifyContent: "space-between", border: "1px solid var(--border-default)", borderRadius: 8, padding: "8px 10px" }}>
                <span><strong>{role}</strong> · {device.profileId} ({device.protocol})</span>
                <button className="button" onClick={() => removeDevice(selectedRoom.id, role)}>Remove</button>
              </div>
            ))}
            {Object.keys(selectedRoom.devices).length === 0 && <p className="subhead">No assigned devices yet.</p>}
          </div>
        </div>
      )}

      <div className="card" style={{ marginTop: 16 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}>
          <p className="label" style={{ margin: 0 }}>Transfer / Feedback Proof</p>
          <button className="button" onClick={handleRefreshProof} disabled={proofLoading}>
            {proofLoading ? "Checking..." : "Run Proof Check"}
          </button>
        </div>

        {proofError && <p style={{ color: "var(--danger)", fontWeight: 600 }}>{proofError}</p>}

        {proof && proof.ready && (
          <>
            <p className="subhead" style={{ marginBottom: 8 }}>
              Transfer ready: <strong>{proof.transferReady ? "yes" : "no"}</strong> · Join count: <strong>{proof.joinCount ?? 0}</strong>
            </p>

            <div style={{ overflow: "auto" }}>
              <table className="signal-table">
                <thead>
                  <tr>
                    <th>Integration</th>
                    <th>Configured</th>
                    <th>Instances</th>
                    <th>Feedback Ready</th>
                  </tr>
                </thead>
                <tbody>
                  {(proof.integrationReport ?? []).map((item) => (
                    <tr key={item.integration}>
                      <td style={{ fontWeight: 700 }}>{item.integration}</td>
                      <td>{item.configured ? "yes" : "no"}</td>
                      <td>{item.count}</td>
                      <td>{item.feedbackReady ? "yes" : "no"}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <p className="subhead" style={{ marginTop: 8 }}>{proof.note}</p>
          </>
        )}

        {proof && !proof.ready && (
          <p style={{ color: "var(--warning)", fontWeight: 600 }}>
            {proof.message} {proof.validationError ? `(${proof.validationError})` : ""}
          </p>
        )}
      </div>
    </div>
  );
}
